---
name: "[integration]"

on:  # yamllint disable-line rule:truthy
  pull_request_target:
    branches:
      # skip test for backport branches since it doesn't make sense to test
      # those against osbuild-composer main
      - main

jobs:

  unit-tests:
    name: "🛃 osbuild-composer unit tests"
    runs-on: ubuntu-20.04
    container:
      image: registry.fedoraproject.org/fedora:latest
    outputs:
      # Define job outputs
      # (see https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/passing-information-between-jobs#example-defining-outputs-for-a-job)
      # Define one output for the test with the merge base and one for the test
      # agains the PR
      base_test: ${{ steps.tests-base.outputs.base_test }}
      pr_test: ${{ steps.tests-pr.outputs.pr_test }}

    steps:
      # krb5-devel is needed to test internal/upload/koji package
      # gcc is needed to build the mock depsolver binary for the unit tests
      # gpgme-devel is needed for container upload dependencies
      - name: Install build and test dependencies
        run: dnf -y install krb5-devel gcc git-core go gpgme-devel osbuild-depsolve-dnf btrfs-progs-devel device-mapper-devel

      - name: Check out osbuild-composer main branch
        uses: actions/checkout@v4
        with:
          path: osbuild-composer
          repository: osbuild/osbuild-composer
          ref: main

      - name: Check out osbuild/images for the PR
        uses: actions/checkout@v4
        with:
          path: images
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Mark the working directory as safe for git
        run: git config --global --add safe.directory "$(pwd)"

      - name: Update the osbuild/images reference to the merge base with main
        env:
          merge_base_sha: ${{ github.event.pull_request.base.sha }}
        run: |
          cd osbuild-composer
          go mod edit -replace github.com/osbuild/images=github.com/achilleas-k/images-message-test@$merge_base_sha
          ./tools/prepare-source.sh

      - name: Run unit tests (merge base)
        working-directory: osbuild-composer
        id: tests-base
        # This step will not fail if the test fails, but it will write the
        # failure to GITHUB_OUTPUT
        run: |
          if go test -v -race ./...; then
            echo "base_test=1" >> $GITHUB_OUTPUT
          else
            echo "base_test=0" >> $GITHUB_OUTPUT
          fi

      - name: Update the osbuild/images reference to the PR HEAD
        env:
          pr_head: ${{ github.event.pull_request.hase.sha }}
        # Restore and clean the checkout and replace the dependency again using
        # images from the checkout above
        run: |
          cd osbuild-composer
          git restore .
          git clean -xfd .
          go mod edit -replace github.com/osbuild/images=../images
          ./tools/prepare-source.sh

      - name: Run unit tests (PR HEAD)
        id: tests-pr
        working-directory: osbuild-composer
        # This step will not fail if the test fails, but it will write the
        # failure to GITHUB_OUTPUT
        run: |
          if go test -v -race ./...; then
            echo "pr_test=1" >> $GITHUB_OUTPUT
          else
            echo "pr_test=0" >> $GITHUB_OUTPUT
          fi

  post-results:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Create comment
        id: create-message
        env:
          base_test: ${{ needs.unit-tests.outputs.base_test }}
          pr_test: ${{ needs.unit-tests.outputs.pr_test }}
        # Create the appropriate comment (if necessary) to post on the PR
        # See https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#multiline-strings
        run: |
          if (( base_test == 1 )) && (( pr_test == 0 )); then
            {
              echo 'message<<EOF'
              This PR changes the images API or behaviour. The next update of the images dependency in osbuild-composer will need work to adapt to these changes.
              This is simply a notice. It will not block this PR from being merged.
              echo EOF
            } >> $GITHUB_OUTPUT
          fi

      - name: Add comment
        uses: mshick/add-pr-comment@v2
        # Use default token here
        # repo-token: ${{ secrets.SCHUTZBOT_GITHUB_ACCESS_TOKEN }}
        env:
          message: ${{ steps.create-message.outputs.message }}
        with:
          issue: ${{ github.event.pull_request.number }}
          message: ${{ env.message }}
